//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica_Catalogo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Roles
    {
        public Roles()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }

        [Key]
        [Display(Name = "ID")]
        public int idRol { get; set; }

        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El nombre del rol es obligatorio.")]
        public string Nombre { get; set; }


        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
